# stage - build
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# stage - prod
FROM node:22-alpine AS prod

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/dist ./dist
COPY package*.json ./
RUN npm ci --omit=dev 

EXPOSE 9000
CMD ["npm", "run", "start:docker"]
